Repository guibranco/pancake, pull requests merged in 2024-07, with the labels that each got.

#149 Color class
  docs/user-guide/color.md
  src/Color.php
  tests/ColorTest.php
Labels: documentation, enhancement, help wanted, good first issue, size/L, hacktoberfest, 🛠 WIP

#155 Update version +semver: feature
  docs/changelog.md
  docs/user-guide/basic-usage.md
Labels: documentation, enhancement, size/XS, ☑️ auto-merge

#168 Update HealthChecksTest.php
  tests/HealthChecksTest.php
Labels: size/XS, ☑️ auto-merge

#169 Add log method to HealthChecks
  docs/user-guide/health-checks.md
  src/HealthChecks.php
  tests/HealthChecksTest.php
Labels: size/M, ☑️ auto-merge

#170 Create infisical-secrets-check.yml
  .github/workflows/infisical-secrets-check.yml
Labels: size/M, ☑️ auto-merge

#174 Update README.md
  README.md
Labels: size/XS, ☑️ auto-merge

#182 Update basic-usage.md
  docs/user-guide/basic-usage.md
Labels: size/XS, ☑️ auto-merge

#186 Update contributors-readme.yml
  .github/workflows/contributors-readme.yml
Labels: size/XS, ☑️ auto-merge

#189 Add ShieldsIo class +semver: minor
  composer.lock
  docs/changelog.md
  docs/user-guide/basic-usage.md
  docs/user-guide/shieldsio.md
  src/ShieldsIo.php
  tests/ShieldsIoTest.php
Labels: documentation, enhancement, help wanted, good first issue, size/L, hacktoberfest, ☑️ auto-merge

#190 Update documentation
  docs/user-guide/shieldsio.md
Labels: size/XS, ☑️ auto-merge
