Repository guibranco/pancake, pull requests merged in 2024-10, with the labels that each got.

#227 Enhance Request Handling in Request.php +semver: minor
  docs/changelog.md
  docs/user-guide/request.md
  src/Request.php
Labels: enhancement, size/L, ☑️ auto-merge, Review effort [1-5]: 2

#228 Refactor HTTP request methods in documentation
  docs/user-guide/request.md
Labels: enhancement, size/S, ☑️ auto-merge, Review effort [1-5]: 2

#229 Enhance HTTP Request Methods in Request.php
  src/Constants.php
  src/HealthChecks.php
  src/Logger.php
  src/OneSignal.php
  src/Request.php
  tests/RequestTest.php
Labels: documentation, enhancement, size/M, ☑️ auto-merge, Review effort [1-5]: 2

#240 Added SessionManager class with advanced session handling features
  docs/user-guide/session-manager.md
  src/SessionManager.php
Labels: 📝 documentation, enhancement, help wanted, good first issue, size/L, hacktoberfest, 🧪 tests, 🚦 awaiting triage, ⏳ waiting response, 🕓 medium effort

#246 Create SessionManagerTest.php +semver: minor
  .githooks/prepare-commit-msg
  .vscode/settings.json
  composer.lock
  src/SessionManager.php
  tests/SessionManagerTest.php
Labels: 📝 documentation, enhancement, size/L, ☑️ auto-merge, 🧪 tests, ♻️ code quality, 🧑‍💻 tech-debit, 🕓 medium effort

#247 docs - Updated documentation for Session Manager and features
  docs/changelog.md
  docs/user-guide/basic-usage.md
  docs/user-guide/color.md
  docs/user-guide/session-manager.md
Labels: size/L, ☑️ auto-merge

#248 docs - Updated documentation in index and basic usage files +semver: skip
  docs/index.md
  docs/user-guide/basic-usage.md
Labels: size/L, ☑️ auto-merge

#254 Update changelog.md +semver: minor
  docs/changelog.md
Labels: size/XS, ☑️ auto-merge

#250 Add a database class for MySQL/MariaDB +semver: minor
  .github/workflows/build.yml
  .github/workflows/ci.yml
  .github/workflows/codacy.yml
  .github/workflows/code-climate.yml
  .github/workflows/codecov.yml
  .github/workflows/codeql.yml
  .github/workflows/deep-source.yml
  .github/workflows/infisical-secrets-check.yml
  .github/workflows/sonar-cloud.yml
  .vscode/settings.json
  CODE_OF_CONDUCT.md
  README.md
  docker-compose.yml
  docs/changelog.md
  docs/user-guide/basic-usage.md
  docs/user-guide/color.md
  docs/user-guide/database.md
  docs/user-guide/guid-v4.md
  docs/user-guide/health-checks.md
  docs/user-guide/logger.md
  docs/user-guide/one-signal.md
  docs/user-guide/request.md
  src/Database/Database.php
  src/Database/DatabaseException.php
  src/Database/DatabaseOptions.php
  src/Database/IDatabase.php
  src/IpUtils.php
  tests/Integration/DatabaseTest.php
  tests/Integration/RequestTest.php
  tests/Unit/ColorTest.php
  tests/Unit/DatabaseExceptionTest.php
  tests/Unit/DatabaseOptionsTest.php
  tests/Unit/EmailTest.php
  tests/Unit/GUIDv4Test.php
  tests/Unit/HealthChecksTest.php
  tests/Unit/IpUtilsTest.php
  tests/Unit/LoggerTest.php
  tests/Unit/MemoryCacheTest.php
  tests/Unit/OneSignalTest.php
  tests/Unit/SessionManagerTest.php
  tests/Unit/ShieldsIoTest.php
  tests/phpunit.xml
Labels: 📝 documentation, enhancement, size/XXL, hacktoberfest, ☑️ auto-merge, 🧪 tests, 🕔 high effort

#255 Update index.md +semver: skip
  docs/index.md
Labels: size/S, ☑️ auto-merge

#256 Update basic-usage.md +semver: skip
  docs/user-guide/basic-usage.md
Labels: size/XS, ☑️ auto-merge
