Repository guibranco/pancake, pull requests merged in 2025-04, with the labels that each got.

#345 Update changelog.md
  docs/changelog.md
Labels: size/XS, ☑️ auto-merge, Review effort [1-5]: 1, documentation

#347 add sonarQube using sonarqube-scan-action
  .github/workflows/sonar-cloud.yml
Labels: enhancement, size/XS, Review effort [1-5]: 2, 🚦 awaiting triage

#360 Update ci.yml
  .github/workflows/ci.yml
Labels: enhancement, size/S, ☑️ auto-merge, Review effort [1-5]: 2, Other

#358 Create wait-for-healthy.sh
  tools/wait-for-healthy.sh
Labels: enhancement, size/M, ☑️ auto-merge, Review effort [1-5]: 2

#359 Update build.yml
  .github/workflows/build.yml
  tools/wait-for-healthy.sh
Labels: enhancement, size/S, ☑️ auto-merge, Review effort [1-5]: 2

#364 Update code-climate.yml
  .github/workflows/code-climate.yml
Labels: enhancement, size/XS, ☑️ auto-merge, Review effort [1-5]: 2

#365 Update codecov.yml
  .github/workflows/codecov.yml
Labels: enhancement, size/XS, ☑️ auto-merge, Review effort [1-5]: 2

#367 Update sonar-cloud.yml
  .github/workflows/sonar-cloud.yml
Labels: enhancement, size/M, ☑️ auto-merge, Review effort [1-5]: 2

#366 Update deep-source.yml
  .github/workflows/deep-source.yml
Labels: enhancement, size/XS, ☑️ auto-merge, Review effort [1-5]: 2

#368 Delete tests/check-wiremock.php
  tests/check-wiremock.php
Labels: size/M, ☑️ auto-merge, Review effort [1-5]: 1, Other

#369 Update wait-for-healthy.sh
  tools/wait-for-healthy.sh
Labels: enhancement, size/S, ☑️ auto-merge, Review effort [1-5]: 2, documentation
